version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vt
      POSTGRES_PASSWORD: vt
      POSTGRES_USER: vt
  flyway:
    image: flyway/flyway:8.3
    command: -url=jdbc:postgresql://postgres/vt -user=vt -password=vt -connectRetries=60 migrate
    environment:
      DATABASE_HOST: postgres
      DATABASE_USER: vt
      DATABASE_PASSWORD: vt
      DATABASE_NAME: vt
    depends_on:
      - postgres
    volumes:
      - "${PWD}/sql:/flyway/sql"
