version: "3.9"
services:
  postgres:
    image: postgres:14.1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vt
      POSTGRES_PASSWORD: password
      POSTGRES_USER: vt
  flyway:
    image: flyway/flyway:8.3
    command: -url=jdbc:postgresql://postgres/vt -user=vt -password=password -connectRetries=60 migrate
    depends_on:
      - postgres
    volumes:
      - "${PWD}/sql:/flyway/sql"
